In [3]:
# https://openclassrooms.com/fr/courses/7410486-nettoyez-et-analysez-votre-jeu-de-donnees/exercises/4257

In [2]:
# imports

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [46]:
pd.set_option('display.max_rows', 750)
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', None)

In [1]:
ls -lh

total 1,1M
-rw-r--r-- 1 mijka mijka  11K 10 août  10:13  course+-+Quiz+P2.csv
-rw-r--r-- 1 mijka mijka  18K  4 févr.  2022  operations.csv
-rw-r--r-- 1 mijka mijka    0  4 févr.  2022  operations.csv:Zone.Identifier
-rw-r--r-- 1 mijka mijka 449K  4 févr.  2022 'Python - Décrivez et nettoyez votre jeu de données.ipynb'
-rw-r--r-- 1 mijka mijka    0  4 févr.  2022 'Python - Décrivez et nettoyez votre jeu de données.ipynb:Zone.Identifier'
-rw-r--r-- 1 mijka mijka 594K  4 févr.  2022 'R - Décrivez et nettoyez votre jeu de données.ipynb'
-rw-r--r-- 1 mijka mijka    0  4 févr.  2022 'R - Décrivez et nettoyez votre jeu de données.ipynb:Zone.Identifier'
-rw-r--r-- 1 mijka mijka   72 10 août  10:14  Untitled.ipynb


In [4]:
df = pd.read_csv('course+-+Quiz+P2.csv', low_memory=False)

In [5]:
df.head()

,Position,Sexe,Temps,Dept,Temps_secondes,Age
0,1,M,00:32:23,76,779543,40.0
1,2,M,00:32:40,27,779560,34.0
2,3,M,00:33:15,76,779595,44.0
3,4,M,00:33:23,76,779603,46.0
4,5,M,00:33:29,76,779609,26.0


In [6]:
df.shape

(340, 6)

In [8]:
df.columns

Index(['Position', 'Sexe', 'Temps', 'Dept', 'Temps_secondes', 'Age'], dtype='object')

In [13]:
df['Dept'].unique()

array([76, 27, 14, 78])

In [15]:
nb_na = df.isnull().sum()
nb_na[nb_na>0]

Sexe    2
Age     4
dtype: int64

In [18]:
import datetime as dt

In [25]:
#df['Temps'] = pd.to_datetime(df['Temps'])

In [24]:
df.loc[df['Temps']=='54min47s']

,Position,Sexe,Temps,Dept,Temps_secondes,Age
250,251,M,54min47s,27,780887,42.0


In [27]:
df.describe()

,Position,Dept,Temps_secondes,Age
count,340.000000,340.000000,340.000000,336.000000
mean,177.061765,56.991176,780553.123529,42.145833
std,166.584054,25.059279,514.526264,13.963690
min,-100.000000,14.000000,779543.000000,18.000000
25%,85.750000,27.000000,780200.500000,34.000000
50%,170.500000,76.000000,780536.500000,41.500000
75%,255.250000,76.000000,780906.500000,49.250000
max,2640.000000,78.000000,781831.000000,174.000000


In [28]:
df.loc[df['Position']==2640]

,Position,Sexe,Temps,Dept,Temps_secondes,Age
264,2640,M,00:56:21,76,780981,51.0


In [51]:
# 2 outliers : -100, 2640
df['Position'].unique()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43, -100,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [36]:
# 2 outliers : nan, 174
df['Age'].unique()

array([ 40.,  34.,  44.,  46.,  26.,  22.,  37.,  25.,  48.,  30.,  35.,
        29.,  32.,  52.,  59.,  42.,  43.,  55.,  24.,  45.,  33.,  31.,
        39.,  38.,  28.,  53.,  21.,  49.,  36.,  65.,  61.,  nan,  57.,
        66.,  64.,  67.,  50.,  41.,  23.,  19.,  18.,  68.,  51.,  47.,
        27.,  72.,  60.,  20.,  71.,  56.,  54.,  63.,  58.,  73.,  62.,
       174.,  70.])

In [38]:
df['Temps_secondes'].unique()

array([779543, 779560, 779595, 779603, 779609, 779614, 779619, 779621,
       779624, 779656, 779660, 779663, 779669, 779670, 779685, 779705,
       779712, 779757, 779772, 779775, 779780, 779782, 779783, 779795,
       779802, 779811, 779812, 779824, 779827, 779828, 779839, 779845,
       779847, 779849, 779851, 779857, 779858, 779865, 779875, 779877,
       779899, 779922, 779979, 779985, 779989, 779990, 779991, 779996,
       779998, 780016, 780017, 780018, 780027, 780031, 780037, 780039,
       780041, 780044, 780059, 780061, 780073, 780083, 780090, 780091,
       780101, 780103, 780107, 780110, 780116, 780122, 780125, 780126,
       780139, 780156, 780166, 780169, 780178, 780187, 780195, 780198,
       780199, 780201, 780204, 780206, 780209, 780211, 780215, 780216,
       780217, 780226, 780230, 780234, 780237, 780239, 780247, 780250,
       780253, 780259, 780260, 780261, 780262, 780266, 780269, 780276,
       780279, 780281, 780285, 780286, 780287, 780288, 780289, 780298,
      

In [40]:
df['Temps_secondes'].nunique()

300

In [61]:
df.count()

Position          340
Sexe              338
Temps             340
Dept              340
Temps_secondes    340
Age               336
dtype: int64

In [50]:
df['Temps_secondes'].value_counts()[df['Temps_secondes'].value_counts() > 1]

780607    3
781567    3
781168    3
780653    3
780336    2
780346    2
780981    2
779827    2
780269    2
781217    2
780743    2
781026    2
780369    2
780725    2
780785    2
780073    2
781050    2
780665    2
780041    2
780308    2
780687    2
780699    2
781105    2
780298    2
780139    2
780896    2
781771    2
780866    2
780506    2
780549    2
780555    2
781450    2
781496    2
780943    2
780935    2
780453    2
Name: Temps_secondes, dtype: int64

In [53]:
df.loc[df.duplicated(keep=False),:]

,Position,Sexe,Temps,Dept,Temps_secondes,Age


In [59]:
df['Sexe'].unique()

array(['M', 'F', 'O', nan], dtype=object)

In [63]:
df['Sexe'].value_counts()

M    244
F     92
O      2
Name: Sexe, dtype: int64

In [60]:
df['Temps_secondes'].count()

340

In [62]:
df['Dept'].unique()

array([76, 27, 14, 78])